os: linux
dist: focal
language: minimal
services:
- docker
script:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker build --build-arg MINECRAFT_VERSION=$MINECRAFT_VERSION -t voltairemc/spigot-server:$MINECRAFT_VERSION .
- docker push voltairemc/spigot-server:$MINECRAFT_VERSION
env:
  global:
  - secure: IejQB8KCmE2KFi+a/VUVOr99r9XnIsgrUYmHtDEHwBK+Yb9djPl4t00S1n/7ywZsWg52f4D6oyHl/yCudo5WCeae1KCtlSwa0kIB6ca4p6aG6EEMAclv78ZopdegGBo9JbLMQburKrUQgFGpysVC1ktK4DHQ0AZF02Csv7pw31d34eDLchFjl57tWIsfug3OumzFYD/amII8fKmGLSXr164b7oZDEUhd76IHq1a1ppD7oEqCfOt/29JyXzK+Wb67bd4SXqc8ru9urcpEIzazZRnbay2iJDiB2Zt/kwJCIvd/q/SVws2fSy9QXNuuczzl8rWa2zRYwipzwAyU2RgCx83ggr7Czem3cDBuvmzUkApYySiDrcyaILywKAXtbhgHSzOeQ5nGj/tmq39fLKrEMozEC/hMgYfvfw1+hjreRKkmxvuyQOhsgL/enM2VCyT+jG1QibKRqFPGtR8rOCqRw+ZVS41HFdVSC/XMjZNg0J7mVGqQEAwDV87yO9/VH1QzmxGfFpiGU49pjyeCsAvTVN6QYxqb7fH34LXkUVcjzr7O37Q2+7S4uOFj3rm2aVaA5T5vhv6/qVgCDT2yo9I62txSvZpgAiQp17FM8pBzyEm9XF+28W5Yqvtcy5aQAQTmioHy4TQ6NH1uJbO4lBKUMOg6Sj0yqq+qe4eidKUMDGM=
  - secure: B06FjshV+hb/eXcEpZmx4qo/YXc30h9R1Og36MLSIbnCaoOYMepU6JrS/srp81u/sntlAb9HrKU2H/WaX4KArLP1ASQhFvgNBZHEiDJLSuSKiL5SxblM8nvryA4QvLwERe7Gt2YW1OylVnktlaXCmir151GpruzZQrLPfgQwBnAh9sqfMF//Zse4Kq6kmtK4qAuZ7nbMEg7lFr72Vp+yPZ90mlvZVNy+HQS3L0+ZDnDIqheBjtMoigP9FeqtPDkOSWXILF/Dgui7aYDBm3k2cf9QGQCRABrJaGxg2/b+dsxHl/6gZtJMhwiMa2wu5EqSGeC/iYyFwlehEDGPelChb981DmUjpNe4zi+sfk8Cuv5SRdyjKF0gK3tvqnl+tCeR+JFbIeHv1EcHlQ1Yeyfm3pbnFL84sKIz4V6GGU0ZhIKC247f/qGQJLUBGW1pvmG89/bZMxoAsT6+9n6cQJeXlHKtQiCqvv0dQfdZxWoD6sQGd1lo3lly/VZlQVb6DckvQQtFcGdY5BIf2lmonXkPZpzHMhoJb3qQvQCoUX2eUFI+RQk0vQjHhk7quglo37NWXSRQHBTbp13lGireBbEAasW9KfTkTNSpimmAL4boL2E4ogbwPxzxFl1tiZu5MOoogcks06QgKHPH6DuA1i9aODs9HXpgrKIlq/n5b6IzRtc=
  jobs:
  - MINECRAFT_VERSION=latest
  - MINECRAFT_VERSION=1.16.3
  - MINECRAFT_VERSION=1.16.2
  - MINECRAFT_VERSION=1.16.1
  - MINECRAFT_VERSION=1.16
  - MINECRAFT_VERSION=1.15.2
  - MINECRAFT_VERSION=1.15.1
  - MINECRAFT_VERSION=1.15
  - MINECRAFT_VERSION=1.14.4
  - MINECRAFT_VERSION=1.14.3
  - MINECRAFT_VERSION=1.14.2
  - MINECRAFT_VERSION=1.14.1
  - MINECRAFT_VERSION=1.14
  - MINECRAFT_VERSION=1.13.2
  - MINECRAFT_VERSION=1.13
  - MINECRAFT_VERSION=1.12.2
  - MINECRAFT_VERSION=1.11.2
